# .readthedocs.yaml
version: 2

sphinx:
  configuration: docs/conf.py
  builder: html
  # fail_on_warning: true

build:
  os: ubuntu-22.04
  tools:
    python: mambaforge-4.10.3-10
  output-directory: "$READTHEDOCS_OUTPUT/html"  
  commands:
    - cat docs/environment.yml
    - mamba env create --quiet --name latest --file docs/environment.yml
    - python ./setup.py install --force
